In [1]:
from keras.datasets import cifar10
(x_train,y_train),(x_test,y_test)=cifar10.load_data()


A local file was found, but it seems to be incomplete or outdated because the auto file hash does not match the original value of 6d958be074577803d12ecdefd02955f39262c83c16fe9348329d7fe0b5c001ce so we will re-download the data.
170498071/170498071 [==============================] - 158s 1us/step


In [2]:
x_train.shape

(50000, 32, 32, 3)

In [3]:
x_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [4]:
x_train=x_train/255.0
x_test=x_test/255.0

In [5]:
from keras.models import Sequential
from keras.layers import Dense, Convolution2D, MaxPooling2D, Flatten

In [6]:
model=Sequential()
model.add(Convolution2D(32, kernel_size=(3,3),strides=(1,1),activation='relu',input_shape=(32,32,3)))
model.add(MaxPooling2D(2,2))
model.add(Flatten())
model.add(Dense(32,activation='relu'))
model.add(Dense(16,activation='relu'))
model.add(Dense(10,activation='softmax'))

In [7]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',metrics=['accuracy'])


In [8]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 30, 30, 32)        896       
                                                                 
 max_pooling2d (MaxPooling2  (None, 15, 15, 32)        0         
 D)                                                              
                                                                 
 flatten (Flatten)           (None, 7200)              0         
                                                                 
 dense (Dense)               (None, 32)                230432    
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 10)                170       
                                                        

In [9]:
model.fit(x_train,y_train,epochs=10,validation_data=(x_test,y_test))

Epoch 1/10


1563/1563 [==============================] - 14s 8ms/step - loss: 1.6936 - accuracy: 0.3711 - val_loss: 1.5230 - val_accuracy: 0.4333
Epoch 2/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.3543 - accuracy: 0.5103 - val_loss: 1.3005 - val_accuracy: 0.5329
Epoch 3/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.2357 - accuracy: 0.5581 - val_loss: 1.2992 - val_accuracy: 0.5350
Epoch 4/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.1515 - accuracy: 0.5886 - val_loss: 1.2185 - val_accuracy: 0.5643
Epoch 5/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.0934 - accuracy: 0.6107 - val_loss: 1.1485 - val_accuracy: 0.5892
Epoch 6/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.0480 - accuracy: 0.6262 - val_loss: 1.1601 - val_accuracy: 0.5907
Epoch 7/10
1563/1563 [==============================] - 11s 7ms/step - loss: 1.0041 - accuracy: 0.6439 - val_loss: 1.1273 - val_

Adding some more sets for feature extraction

In [17]:
model = Sequential()
# first set
model.add(Convolution2D(32, kernel_size=(3, 3), strides=(1, 1), activation='relu', padding='same', input_shape=(32, 32, 3)))
model.add(MaxPooling2D(2, 2))  # Adjust pooling size
# second set
model.add(Convolution2D(32, kernel_size=(3, 3), strides=(1, 1), activation='relu', padding='same'))
model.add(MaxPooling2D(2, 2))  # Adjust pooling size
# third set
model.add(Convolution2D(32, kernel_size=(3, 3), strides=(1, 1), activation='relu', padding='same'))
model.add(MaxPooling2D(2, 2))  # Adjust pooling size
# fourth set
model.add(Convolution2D(32, kernel_size=(3, 3), strides=(1, 1), activation='relu', padding='same'))
model.add(MaxPooling2D(2, 2))  # Adjust pooling size

# Flatten the output before dense layers
model.add(Flatten())
# MLP
model.add(Dense(100, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(32, activation='relu'))
# Final layer for output
model.add(Dense(10, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

model.fit(x_train, y_train, epochs=10, validation_data=(x_test, y_test))


Model: "sequential_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d_28 (Conv2D)          (None, 32, 32, 32)        896       
                                                                 
 max_pooling2d_22 (MaxPooli  (None, 16, 16, 32)        0         
 ng2D)                                                           
                                                                 
 conv2d_29 (Conv2D)          (None, 16, 16, 32)        9248      
                                                                 
 max_pooling2d_23 (MaxPooli  (None, 8, 8, 32)          0         
 ng2D)                                                           
                                                                 
 conv2d_30 (Conv2D)          (None, 8, 8, 32)          9248      
                                                                 
 max_pooling2d_24 (MaxPooli  (None, 4, 4, 32)         

In [19]:
# Evaluate the model on the test data
loss, accuracy = model.evaluate(x_test, y_test)
print(f'Test Accuracy: {accuracy}')

313/313 [==============================] - 1s 4ms/step - loss: 0.8379 - accuracy: 0.7079
Test Accuracy: 0.7078999876976013


In [20]:
from sklearn.metrics import confusion_matrix
import numpy as np

# Predict labels for the test set
y_pred = np.argmax(model.predict(x_test), axis=1)

# Create the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Print the confusion matrix
print("Confusion Matrix:")
print(cm)

313/313 [==============================] - 2s 4ms/step
Confusion Matrix:
[[728  24  71  25   9   1   4   7  75  56]
 [ 18 825   9  10   1   1   7   3  22 104]
 [ 55   6 677  69  59  39  45  28  11  11]
 [ 19  10 124 559  36 122  70  42   9   9]
 [ 25   3 123  84 571  30  31 117  14   2]
 [ 11   6  90 258  25 521  13  65   4   7]
 [  6   6  59  76  38  21 768   7   8  11]
 [ 15   2  70  47  32  32   4 779   4  15]
 [ 50  23  31  23   5   3   4   3 826  32]
 [ 22  70  12  20   3   5   9  16  18 825]]
